# Generated by Django 4.2.30 on 2026-09-09 14:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wms_master', '0001_initial'),
        ('wms_platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLot',
            fields=[
                ('lot_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_code', models.CharField(blank=True, max_length=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('mrp', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('box_size', models.IntegerField(default=1)),
                ('inbound_type', models.CharField(choices=[('EXTERNAL', 'External'), ('INTERNAL', 'Internal')], default='EXTERNAL', max_length=10)),
                ('inbound_ref', models.CharField(blank=True, max_length=100)),
                ('source_vendor_id', models.UUIDField(blank=True, null=True)),
                ('bucket', models.CharField(choices=[('Good', 'Good'), ('BAD', 'Bad'), ('QC_HOLD', 'QC Hold'), ('InProgress', 'In Progress')], default='Good', max_length=15)),
                ('qty', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('HELD', 'Held'), ('PICKING', 'Picking'), ('DEPLETED', 'Depleted')], default='AVAILABLE', max_length=10)),
                ('on_hold', models.BooleanField(default=False)),
                ('hold_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='wms_master.bin')),
                ('hold_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_lots', to='wms_platform.user')),
            ],
            options={
                'db_table': 'inventory_lot',
                'ordering': ['expiry_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lpn',
            fields=[
                ('lpn_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('TOTE', 'Tote'), ('CARTON', 'Carton'), ('PALLET', 'Pallet')], default='TOTE', max_length=10)),
                ('current_bin', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('EMPTY', 'Empty'), ('PICKING', 'Picking'), ('SORT_DONE', 'Sort Done'), ('QC_DONE', 'QC Done'), ('IRT_DONE', 'IRT Done'), ('PACKED', 'Packed'), ('IN_TRANSIT', 'In Transit'), ('RECEIVED', 'Received'), ('CLOSED', 'Closed')], default='EMPTY', max_length=15)),
                ('is_superstore', models.BooleanField(default=False)),
                ('order_id', models.UUIDField(blank=True, null=True)),
                ('picklist_id', models.UUIDField(blank=True, null=True)),
                ('qc_at', models.DateTimeField(blank=True, null=True)),
                ('irt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lpns', to='wms_master.site')),
                ('dest_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dest_lpns', to='wms_master.site')),
                ('irt_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='irt_lpns', to='wms_platform.user')),
                ('parent_pallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='wms_inventory.lpn')),
                ('qc_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_lpns', to='wms_platform.user')),
                ('source_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_lpns', to='wms_master.site')),
            ],
            options={
                'db_table': 'lpn',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTx',
            fields=[
                ('tx_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_bin', models.CharField(blank=True, max_length=100)),
                ('to_bin', models.CharField(blank=True, max_length=100)),
                ('qty', models.IntegerField(default=0)),
                ('flow', models.CharField(choices=[('GRN', 'GRN'), ('PUTAWAY', 'Putaway'), ('PICK', 'Pick'), ('SORT', 'Sort'), ('PACK', 'Pack'), ('SHIP', 'Ship'), ('RECEIVE', 'Receive'), ('MOVEMENT', 'Movement'), ('ADJUST', 'Adjust'), ('SCRAP', 'Scrap'), ('REINVENTORIZE', 'Re-inventorize'), ('COUNT', 'Count')], max_length=20)),
                ('ref_type', models.CharField(blank=True, max_length=50)),
                ('ref_id', models.UUIDField(blank=True, null=True)),
                ('remark', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_txs', to='wms_inventory.inventorylot')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wms_master.site')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wms_master.sku')),
                ('to_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_txs', to='wms_inventory.inventorylot')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='wms_platform.user')),
            ],
            options={
                'db_table': 'inventory_tx',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='lpn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='wms_inventory.lpn'),
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='parent_pallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pallet_lots', to='wms_inventory.lpn'),
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='wms_master.site'),
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='wms_master.sku'),
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='source_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourced_lots', to='wms_master.site'),
        ),
        migrations.CreateModel(
            name='Droplist',
            fields=[
                ('droplist_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('totes', models.IntegerField(default=0)),
                ('dropped_count', models.IntegerField(default=0)),
                ('in_spider_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='OPEN', max_length=15)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='droplists', to='wms_platform.user')),
                ('lpn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='droplists', to='wms_inventory.lpn')),
            ],
            options={
                'db_table': 'droplist',
                'ordering': ['-created_at'],
            },
        ),
    ]
