# Generated by Django 4.2.30 on 2026-09-09 14:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wms_inventory', '0001_initial'),
        ('wms_master', '0001_initial'),
        ('wms_platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asn',
            fields=[
                ('asn_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asn_no', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('VENDOR_PO', 'Vendor PO'), ('MH_TRANSFER', 'MH Transfer'), ('STORE_RETURN', 'Store Return'), ('RTV_IN', 'RTV In')], max_length=20)),
                ('po_ref', models.CharField(blank=True, max_length=100)),
                ('slot_start', models.DateTimeField(blank=True, null=True)),
                ('slot_end', models.DateTimeField(blank=True, null=True)),
                ('expected_vehicle', models.CharField(blank=True, max_length=50)),
                ('total_lpns', models.IntegerField(default=0)),
                ('total_skus', models.IntegerField(default=0)),
                ('total_qty', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived'), ('CHECKED_IN', 'Checked In'), ('UNLOADED', 'Unloaded'), ('QC_PENDING', 'QC Pending'), ('PUTAWAY_PENDING', 'Putaway Pending'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dest_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_asns', to='wms_master.site')),
                ('door', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asns', to='wms_master.dockdoor')),
                ('source_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_asns', to='wms_master.site')),
                ('source_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asns', to='wms_master.vendor')),
            ],
            options={
                'db_table': 'asn',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AsnLine',
            fields=[
                ('line_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ean', models.CharField(blank=True, max_length=50)),
                ('ordered_qty', models.IntegerField(default=0)),
                ('expected_expiry', models.DateField(blank=True, null=True)),
                ('line_status', models.CharField(choices=[('OPEN', 'Open'), ('PARTIAL', 'Partial'), ('RECEIVED', 'Received'), ('SHORT', 'Short')], default='OPEN', max_length=10)),
                ('asn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='wms_inbound.asn')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asn_lines', to='wms_master.sku')),
            ],
            options={
                'db_table': 'asn_line',
            },
        ),
        migrations.CreateModel(
            name='Grn',
            fields=[
                ('grn_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grn_no', models.CharField(max_length=50, unique=True)),
                ('mode', models.CharField(choices=[('LPN_SCAN', 'LPN Scan'), ('CASE_SCAN', 'Case Scan'), ('PIECE', 'Piece'), ('FILE', 'File')], default='LPN_SCAN', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('PARTIAL', 'Partial'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=15)),
                ('has_discrepancy', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grns', to='wms_inbound.asn')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grns', to='wms_platform.user')),
            ],
            options={
                'db_table': 'grn',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GrnLine',
            fields=[
                ('line_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordered_qty', models.IntegerField(default=0)),
                ('received_qty', models.IntegerField(default=0)),
                ('damaged_qty', models.IntegerField(default=0)),
                ('expired_qty', models.IntegerField(default=0)),
                ('excess_qty', models.IntegerField(default=0)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('mrp', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('asn_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grn_lines', to='wms_inbound.asnline')),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='wms_inbound.grn')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grn_lines', to='wms_inventory.inventorylot')),
                ('reason_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grn_lines', to='wms_platform.reasoncode')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grn_lines', to='wms_master.sku')),
            ],
            options={
                'db_table': 'grn_line',
            },
        ),
        migrations.CreateModel(
            name='PutawayTask',
            fields=[
                ('putaway_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_location', models.CharField(default='RECV-STAGE', max_length=100)),
                ('priority', models.IntegerField(default=5)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('COMPLETED', 'Completed'), ('EXCEPTION', 'Exception')], default='CREATED', max_length=15)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('exception_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='putaway_tasks', to='wms_platform.user')),
                ('grn_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='putaway_tasks', to='wms_inbound.grnline')),
                ('lpn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='putaway_tasks', to='wms_inventory.lpn')),
                ('to_bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='putaway_tasks', to='wms_master.bin')),
            ],
            options={
                'db_table': 'putaway_task',
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InboundDiscrepancy',
            fields=[
                ('disc_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('SHORT', 'Short'), ('EXCESS', 'Excess'), ('DAMAGE', 'Damage'), ('WRONG_MRP', 'Wrong MRP')], max_length=10)),
                ('claimed_qty', models.IntegerField(default=0)),
                ('found_qty', models.IntegerField(default=0)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='wms_inbound.asn')),
                ('checker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_discrepancies', to='wms_platform.user')),
                ('maker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_discrepancies', to='wms_platform.user')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='wms_master.sku')),
            ],
            options={
                'db_table': 'inbound_discrepancy',
                'ordering': ['-created_at'],
            },
        ),
    ]
