# Generated by Django 5.1.15 on 2026-09-04 10:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_on_hand', models.IntegerField(default=0)),
                ('quantity_reserved', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('available', 'Available'), ('quarantine', 'Quarantine'), ('damaged', 'Damaged'), ('reserved', 'Reserved')], default='available', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='catalog.batch')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='master_data.location')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='master_data.warehouse')),
            ],
            options={
                'verbose_name_plural': 'Inventories',
                'indexes': [models.Index(fields=['batch', 'location', 'status', 'quantity_on_hand'], name='idx_inv_fefo_lookup')],
                'unique_together': {('batch', 'location', 'status')},
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('GRN_RECEIPT', 'GRN Inbound Receipt'), ('QC_PASS', 'QC Passed to Available'), ('QC_REJECT', 'QC Rejected to Damaged'), ('PICK_RESERVE', 'Pick Reservation'), ('PICK_CONFIRM', 'Pick Confirmed'), ('PACK_VERIFY', 'Pack Scan Verified'), ('SHIPMENT_DEDUCT', 'Shipment Dispatched'), ('REPLENISHMENT_MOVE', 'Replenishment Transfer'), ('CYCLE_COUNT_ADJUST', 'Cycle Count Adjustment'), ('CUSTOMER_RETURN', 'Customer RMA Return')], max_length=50)),
                ('quantity', models.IntegerField()),
                ('reference_doc_type', models.CharField(max_length=50)),
                ('reference_doc_id', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='catalog.batch')),
                ('dest_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transactions', to='master_data.location')),
                ('source_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transactions', to='master_data.location')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='master_data.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['warehouse', 'transaction_type', '-created_at'], name='idx_inv_txn_type'), models.Index(fields=['batch', '-created_at'], name='idx_inv_txn_batch')],
            },
        ),
    ]
