# Generated by Django 5.1.15 on 2026-09-06 08:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(db_index=True, max_length=50)),
                ('warehouse', models.CharField(default='RJY-DS-001', max_length=50)),
                ('zone', models.CharField(default='Grocery-A', max_length=50)),
                ('aisle', models.CharField(default='A04', max_length=20)),
                ('rack', models.CharField(default='R12', max_length=20)),
                ('shelf', models.CharField(default='S03', max_length=20)),
                ('bin', models.CharField(default='B04', max_length=20)),
                ('location_barcode', models.CharField(default='LOC-A04-R12-S03-B04', max_length=64)),
                ('sku', models.CharField(db_index=True, max_length=64)),
                ('item_name', models.CharField(max_length=200)),
                ('batch_no', models.CharField(max_length=100)),
                ('serial_no', models.CharField(blank=True, max_length=100, null=True)),
                ('available_qty', models.IntegerField(default=0)),
                ('reserved_qty', models.IntegerField(default=0)),
                ('picked_qty', models.IntegerField(default=0)),
                ('quarantine_qty', models.IntegerField(default=0)),
                ('damaged_qty', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=500)),
                ('occupancy_pct', models.CharField(default='0%', max_length=20)),
                ('mfg_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('storage_condition', models.CharField(default='Ambient', max_length=50)),
                ('temperature', models.CharField(default='26°C', max_length=30)),
                ('stock_status', models.CharField(default='Available', max_length=50)),
            ],
            options={
                'ordering': ['location', 'sku'],
            },
        ),
        migrations.CreateModel(
            name='PutawayTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('putaway_id', models.CharField(max_length=50, unique=True)),
                ('inbound_no', models.CharField(db_index=True, max_length=50)),
                ('item_name', models.CharField(max_length=200)),
                ('sku', models.CharField(db_index=True, max_length=64)),
                ('barcode', models.CharField(db_index=True, max_length=64)),
                ('batch_no', models.CharField(max_length=100)),
                ('serial_no', models.CharField(blank=True, max_length=100, null=True)),
                ('accepted_qty', models.IntegerField(default=0)),
                ('putaway_qty', models.IntegerField(default=0)),
                ('pending_qty', models.IntegerField(default=0)),
                ('warehouse', models.CharField(default='RJY-DS-001', max_length=50)),
                ('source_location', models.CharField(default='Dock-03', max_length=50)),
                ('zone', models.CharField(default='Grocery-A', max_length=50)),
                ('aisle', models.CharField(default='A04', max_length=20)),
                ('rack', models.CharField(default='R12', max_length=20)),
                ('shelf', models.CharField(default='S03', max_length=20)),
                ('bin', models.CharField(default='B04', max_length=20)),
                ('destination_location', models.CharField(default='A04-R12-S03-B04', max_length=50)),
                ('location_barcode', models.CharField(default='LOC-A04-R12-S03-B04', max_length=64)),
                ('storage_type', models.CharField(default='Rack', max_length=50)),
                ('capacity', models.IntegerField(default=500)),
                ('occupied_qty', models.IntegerField(default=0)),
                ('available_capacity', models.IntegerField(default=500)),
                ('storage_condition', models.CharField(default='Ambient', max_length=50)),
                ('temperature', models.CharField(default='26°C', max_length=30)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('fefo_priority', models.CharField(default='Medium', max_length=20)),
                ('scanner_id', models.CharField(default='SCN-014', max_length=50)),
                ('operator', models.CharField(default='Arjun', max_length=100)),
                ('status', models.CharField(default='Completed', max_length=50)),
                ('started_at', models.CharField(default='11:50', max_length=30)),
                ('completed_at', models.CharField(blank=True, default='', max_length=30)),
            ],
            options={
                'ordering': ['-putaway_id'],
            },
        ),
    ]
