# Generated by Django 5.1.15 on 2026-09-04 10:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingWebhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('webhook_id', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('event_type', models.CharField(choices=[('inventory.low_stock', 'Inventory Low Stock'), ('grn.received', 'GRN Stock Received'), ('order.shipped', 'Order Shipped'), ('batch.expiring_soon', 'Batch Expiring Soon'), ('backorder.triggered', 'Backorder Triggered')], max_length=50)),
                ('target_url', models.URLField(max_length=255)),
                ('secret_token', models.CharField(default='zippzo-secret-token', max_length=255)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=5)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('last_response_code', models.IntegerField(blank=True, null=True)),
                ('last_error_message', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
