# Generated by Django 4.2.30 on 2026-09-09 14:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wms_inbound', '0001_initial'),
        ('wms_master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trip_no', models.CharField(max_length=50, unique=True)),
                ('direction', models.CharField(choices=[('FORWARD', 'Forward'), ('RETURN', 'Return'), ('INBOUND_MH', 'Inbound MH')], default='FORWARD', max_length=15)),
                ('dest_site', models.CharField(blank=True, max_length=200)),
                ('trip_date', models.DateField(blank=True, null=True)),
                ('batch_slot', models.CharField(blank=True, max_length=50)),
                ('batch_id', models.UUIDField(blank=True, null=True)),
                ('dispatch_plan_id', models.UUIDField(blank=True, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=30)),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('driver_phone', models.CharField(blank=True, max_length=20)),
                ('otr_cutoff', models.DateTimeField(blank=True, null=True)),
                ('otd_cutoff', models.DateTimeField(blank=True, null=True)),
                ('reporting_cutoff', models.DateTimeField(blank=True, null=True)),
                ('dock_in_at', models.DateTimeField(blank=True, null=True)),
                ('dock_out_cutoff', models.DateTimeField(blank=True, null=True)),
                ('gate_out_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lpns_loaded', models.IntegerField(default=0)),
                ('load_weight', models.CharField(blank=True, max_length=20)),
                ('forward_lpns_total', models.IntegerField(default=0)),
                ('delay_status', models.CharField(choices=[('ON_TRACK', 'On Track'), ('DELAYED', 'Delayed')], default='ON_TRACK', max_length=10)),
                ('gps_status', models.CharField(choices=[('LIVE', 'Live'), ('STALE', 'Stale'), ('OFF', 'Off')], default='OFF', max_length=10)),
                ('pod_template', models.CharField(default='LPN_SCANNING', max_length=50)),
                ('billing_status', models.CharField(choices=[('PLANNED', 'Planned'), ('BILLED', 'Billed'), ('PAID', 'Paid')], default='PLANNED', max_length=10)),
                ('billing_basis', models.CharField(blank=True, max_length=50)),
                ('source_system', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('VEHICLE_ASSIGNED', 'Vehicle Assigned'), ('CHECKED_IN', 'Checked In'), ('DOCKED_IN', 'Docked In'), ('LOADING', 'Loading'), ('LOADED', 'Loaded'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paired_master_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paired_trips', to='wms_transport.trip')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='wms_master.site')),
                ('transporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='wms_master.transporter')),
                ('vehicle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='wms_master.vehicletype')),
            ],
            options={
                'db_table': 'trip',
                'ordering': ['-trip_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleCheckin',
            fields=[
                ('checkin_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('OUTBOUND', 'Outbound'), ('INBOUND', 'Inbound')], default='OUTBOUND', max_length=10)),
                ('vehicle_no', models.CharField(max_length=30)),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('driver_phone', models.CharField(blank=True, max_length=20)),
                ('checkin_at', models.DateTimeField(blank=True, null=True)),
                ('checkin_cutoff', models.DateTimeField(blank=True, null=True)),
                ('dl_valid', models.BooleanField(default=True)),
                ('rc_valid', models.BooleanField(default=True)),
                ('six_sided', models.BooleanField(default=True)),
                ('seal_no', models.CharField(blank=True, max_length=50)),
                ('temp_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('security_person', models.CharField(blank=True, max_length=100)),
                ('loading_manifest_id', models.UUIDField(blank=True, null=True)),
                ('unloading_manifest_id', models.UUIDField(blank=True, null=True)),
                ('delay_status', models.CharField(choices=[('ON_TRACK', 'On Track'), ('DELAYED', 'Delayed')], default='ON_TRACK', max_length=10)),
                ('breach_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='wms_inbound.asn')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='wms_transport.trip')),
            ],
            options={
                'db_table': 'vehicle_checkin',
                'ordering': ['-checkin_at'],
            },
        ),
        migrations.CreateModel(
            name='TripReturnLeg',
            fields=[
                ('leg_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_lpns', models.IntegerField(default=0)),
                ('lpns_unloaded', models.IntegerField(default=0)),
                ('unload_checkin_at', models.DateTimeField(blank=True, null=True)),
                ('dock_in_cutoff', models.DateTimeField(blank=True, null=True)),
                ('dock_out_cutoff', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RETURN_IN_TRANSIT', 'Return In Transit'), ('RETURNED', 'Returned'), ('CLOSED', 'Closed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_legs', to='wms_transport.trip')),
            ],
            options={
                'db_table': 'trip_return_leg',
                'ordering': ['-created_at'],
            },
        ),
    ]
