# Generated by Django 5.1.15 on 2026-09-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='is_near_expiry',
            field=models.BooleanField(default=False, help_text='Flagged for auto-markdown / liquidation'),
        ),
        migrations.AddField(
            model_name='batch',
            name='markdown_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_perishable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='pack_size',
            field=models.CharField(default='1 Unit', help_text='e.g. 1 L, 500g, Pack of 6', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='sap_material_number',
            field=models.CharField(blank=True, help_text='SAP S/4HANA Material Number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shelf_life_hours',
            field=models.IntegerField(default=720, help_text='Shelf life in hours (e.g. 72h for milk, 48h for bread)'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_temp_zone',
            field=models.CharField(choices=[('ambient', 'Ambient (Dry Storage)'), ('chilled', 'Chilled (2°C - 4°C)'), ('frozen', 'Frozen (-18°C)'), ('produce', 'Fresh Fruits & Vegetables')], default='ambient', max_length=20),
        ),
        migrations.AlterField(
            model_name='batch',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
    ]
