# Generated by Django 5.1.15 on 2026-09-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_batch_is_near_expiry_batch_markdown_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='is_near_expiry',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='markdown_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_perishable',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pack_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sap_material_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shelf_life_hours',
        ),
        migrations.RemoveField(
            model_name='product',
            name='storage_temp_zone',
        ),
        migrations.AlterField(
            model_name='batch',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
