# Generated by Django 4.2.30 on 2026-09-09 14:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('MH', 'Mother Hub'), ('DS', 'Dark Store'), ('SS', 'Super Store'), ('XDOCK', 'Cross Dock')], max_length=10)),
                ('dh_precedence', models.CharField(default='DEFAULT', max_length=50)),
                ('ss_precedence', models.CharField(default='SS_DEFAULT', max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('parent_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_sites', to='wms_master.site')),
            ],
            options={
                'db_table': 'site',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('transporter_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('billing_basis', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
            ],
            options={
                'db_table': 'transporter',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('vt_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('capacity_lpns', models.IntegerField(default=0)),
                ('temp_controlled', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'vehicle_type',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('org_entity', models.CharField(blank=True, max_length=50)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_sku_vendor', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
            ],
            options={
                'db_table': 'vendor',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('zone_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('zone_type', models.CharField(choices=[('GENERAL', 'General'), ('MRP', 'MRP'), ('FLEXI_FORWARD', 'Flexi Forward')], default='GENERAL', max_length=20)),
                ('value_type', models.CharField(default='General', max_length=50)),
                ('fragility', models.CharField(default='General', max_length=50)),
                ('food_type', models.CharField(default='General', max_length=50)),
                ('product_type', models.CharField(default='Food', max_length=50)),
                ('is_advance_zone', models.BooleanField(default=False)),
                ('commingled_allowed', models.BooleanField(default=True)),
                ('max_commingled', models.IntegerField(default=5)),
                ('is_hazardous_allowed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLOCKED', 'Blocked')], default='ACTIVE', max_length=10)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='wms_master.site')),
            ],
            options={
                'db_table': 'zone',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SkuCategory',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='wms_master.skucategory')),
            ],
            options={
                'verbose_name_plural': 'SKU Categories',
                'db_table': 'sku_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('sku_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('ean', models.CharField(max_length=50, unique=True)),
                ('sub_category', models.CharField(blank=True, max_length=100)),
                ('mrp', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pack_size', models.CharField(blank=True, max_length=50)),
                ('storage_zone', models.CharField(choices=[('DRY', 'Dry'), ('COLD', 'Cold'), ('FROZEN', 'Frozen')], default='DRY', max_length=10)),
                ('shelf_life_days', models.IntegerField(default=365)),
                ('is_food', models.BooleanField(default=True)),
                ('wac', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skus', to='wms_master.skucategory')),
            ],
            options={
                'db_table': 'sku',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DockDoor',
            fields=[
                ('door_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('capability', models.CharField(choices=[('LOAD', 'Load'), ('UNLOAD', 'Unload'), ('BOTH', 'Both')], default='BOTH', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('BUSY', 'Busy'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dock_doors', to='wms_master.site')),
            ],
            options={
                'db_table': 'dock_door',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ClusterZone',
            fields=[
                ('cz_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('slot_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_zones', to='wms_master.site')),
            ],
            options={
                'db_table': 'cluster_zone',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('bin_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('aisle', models.CharField(blank=True, max_length=20)),
                ('rack', models.CharField(blank=True, max_length=20)),
                ('level', models.IntegerField(default=1)),
                ('level_class', models.CharField(blank=True, max_length=50)),
                ('rack_class', models.CharField(blank=True, max_length=50)),
                ('roll_no', models.IntegerField(default=0)),
                ('bin_type', models.CharField(blank=True, max_length=50)),
                ('lbh', models.CharField(blank=True, max_length=50)),
                ('putaway_max', models.IntegerField(default=100)),
                ('condition', models.CharField(choices=[('GOOD', 'Good'), ('DAMAGE', 'Damage')], default='GOOD', max_length=10)),
                ('is_pickzone', models.BooleanField(default=False)),
                ('zone_sub_type', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='wms_master.site')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bins', to='wms_master.zone')),
            ],
            options={
                'db_table': 'bin',
                'ordering': ['code'],
            },
        ),
    ]
