# Generated by Django 4.2.30 on 2026-09-09 14:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wms_inbound', '0001_initial'),
        ('wms_master', '0001_initial'),
        ('wms_outbound', '0001_initial'),
        ('wms_platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossDockBatch',
            fields=[
                ('xdb_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_no', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('INWARDING', 'Inwarding'), ('SORTING', 'Sorting'), ('COMPLETED', 'Completed')], default='UPLOADED', max_length=15)),
                ('processing_type', models.CharField(default='LPN_BASED', max_length=20)),
                ('orders_count', models.IntegerField(default=0)),
                ('ordered_qty', models.IntegerField(default=0)),
                ('ordered_skus', models.IntegerField(default=0)),
                ('inwarded_qty', models.IntegerField(default=0)),
                ('inwarded_short', models.IntegerField(default=0)),
                ('sorted_qty', models.IntegerField(default=0)),
                ('sorted_short', models.IntegerField(default=0)),
                ('cancelled_skus', models.IntegerField(default=0)),
                ('xdock_allocable_qty', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xdock_batches', to='wms_platform.user')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xdock_batches', to='wms_master.site')),
            ],
            options={
                'db_table': 'cross_dock_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrossDockLine',
            fields=[
                ('line_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty', models.IntegerField(default=0)),
                ('xdock_bin', models.CharField(blank=True, max_length=100)),
                ('allocatable_qty', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ALLOCATED', 'Allocated'), ('SORTED', 'Sorted'), ('SHIPPED', 'Shipped')], default='PENDING', max_length=15)),
                ('asn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xdock_lines', to='wms_inbound.asn')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xdock_lines', to='wms_outbound.order')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xdock_lines', to='wms_master.sku')),
                ('xdb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='wms_crossdock.crossdockbatch')),
            ],
            options={
                'db_table': 'cross_dock_line',
            },
        ),
    ]
