# Generated by Django 5.1.15 on 2026-09-04 10:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fulfillment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shipment_number', models.CharField(max_length=50, unique=True)),
                ('package_weight_kg', models.DecimalField(decimal_places=3, max_digits=8)),
                ('package_dimensions', models.JSONField(default=dict)),
                ('logistics_partner', models.CharField(choices=[('FedEx', 'FedEx'), ('DHL', 'DHL Express'), ('BlueDart', 'BlueDart'), ('Delhivery', 'Delhivery'), ('Self_Fleet', 'Company Fleet / In-House')], default='FedEx', max_length=50)),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('shipping_label_url', models.TextField(blank=True, null=True)),
                ('delivery_eta', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('labeled', 'Label Created'), ('picked_up', 'Picked Up by Carrier'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed_attempt', 'Delivery Attempt Failed'), ('rto', 'Returned to Origin')], default='labeled', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='fulfillment.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentManifest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manifest_number', models.CharField(max_length=50, unique=True)),
                ('logistics_partner', models.CharField(choices=[('FedEx', 'FedEx'), ('DHL', 'DHL Express'), ('BlueDart', 'BlueDart'), ('Delhivery', 'Delhivery'), ('Self_Fleet', 'Company Fleet / In-House')], max_length=50)),
                ('driver_name', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('driver_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('total_packages', models.IntegerField(default=0)),
                ('departure_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_manifests', to=settings.AUTH_USER_MODEL)),
                ('shipments', models.ManyToManyField(related_name='manifests', to='shipping.shipment')),
            ],
        ),
    ]
