# Generated by Django 5.1.15 on 2026-09-06 08:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentDeliveryDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shipment_id', models.CharField(db_index=True, max_length=50)),
                ('customer', models.CharField(default='Jay', max_length=150)),
                ('delivery_address', models.TextField(default='Rajahmundry')),
                ('delivery_slot', models.CharField(default='14:00–15:00', max_length=50)),
                ('order_value', models.CharField(default='₹1,245', max_length=30)),
                ('payment_method', models.CharField(default='UPI', max_length=50)),
                ('payment_status', models.CharField(default='Paid', max_length=30)),
                ('cod_amount', models.CharField(default='0', max_length=30)),
                ('package_barcode', models.CharField(default='PKG890123', max_length=64)),
                ('shipping_label', models.CharField(default='LAB-009821', max_length=64)),
                ('dispatcher', models.CharField(default='Kiran', max_length=100)),
                ('scanner_id', models.CharField(default='SCN-031', max_length=50)),
                ('transporter', models.CharField(default='Internal Fleet', max_length=100)),
                ('rider_id', models.CharField(default='DP-00152', max_length=50)),
                ('rider_name', models.CharField(default='Suresh', max_length=100)),
                ('vehicle_type', models.CharField(default='Bike', max_length=50)),
                ('vehicle_number', models.CharField(default='AP05CD4521', max_length=50)),
                ('route_sequence', models.IntegerField(default=1)),
                ('dispatch_scan_time', models.CharField(blank=True, default='13:15', max_length=30)),
                ('delivery_otp', models.CharField(default='Verified', max_length=30)),
                ('pod', models.CharField(blank=True, default='POD-8921', max_length=50)),
                ('failed_reason', models.CharField(blank=True, default='', max_length=150)),
                ('return_required', models.CharField(default='No', max_length=10)),
                ('status', models.CharField(default='Delivered', max_length=50)),
            ],
            options={
                'ordering': ['-shipment_id'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shipment_id', models.CharField(max_length=50, unique=True)),
                ('order_id', models.CharField(db_index=True, max_length=50)),
                ('package_id', models.CharField(db_index=True, max_length=50)),
                ('warehouse', models.CharField(default='RJY-DS-001', max_length=50)),
                ('customer', models.CharField(default='Jay', max_length=150)),
                ('delivery_zone', models.CharField(default='RJY-Z03', max_length=50)),
                ('items', models.IntegerField(default=1)),
                ('units', models.IntegerField(default=1)),
                ('packages', models.IntegerField(default=1)),
                ('weight', models.CharField(default='7.8 kg', max_length=30)),
                ('transporter', models.CharField(default='Internal Fleet', max_length=100)),
                ('rider', models.CharField(default='Suresh', max_length=100)),
                ('vehicle', models.CharField(default='AP05CD4521', max_length=50)),
                ('route', models.CharField(default='RT-00421', max_length=50)),
                ('tracking_id', models.CharField(default='TRK-982145', max_length=100)),
                ('dispatch_dock', models.CharField(default='DOCK-02', max_length=50)),
                ('eta', models.CharField(default='14:35', max_length=30)),
                ('dispatch_time', models.CharField(blank=True, default='13:18', max_length=30)),
                ('delivery_time', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.CharField(default='Ready for Dispatch', max_length=50)),
            ],
            options={
                'ordering': ['-shipment_id'],
            },
        ),
        migrations.CreateModel(
            name='ShippingScanHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan_id', models.CharField(max_length=50, unique=True)),
                ('shipment_id', models.CharField(db_index=True, max_length=50)),
                ('package_id', models.CharField(db_index=True, max_length=50)),
                ('scanner_id', models.CharField(default='SCN-031', max_length=50)),
                ('user', models.CharField(default='Kiran', max_length=100)),
                ('scan_type', models.CharField(default='Package Verification', max_length=50)),
                ('location', models.CharField(default='PACK-04', max_length=50)),
                ('result', models.CharField(default='Valid', max_length=30)),
                ('scan_time', models.CharField(default='13:10', max_length=30)),
            ],
            options={
                'ordering': ['-scan_id'],
            },
        ),
    ]
