# Generated by Django 4.2.30 on 2026-09-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms_outbound', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellationputaway',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PENDING_QC', 'Pending QC'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='CREATED', max_length=15),
        ),
    ]
