# Generated by Django 5.1.15 on 2026-09-04 10:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_code', models.CharField(max_length=30, unique=True)),
                ('department', models.CharField(choices=[('admin', 'System Administration'), ('management', 'Warehouse Management'), ('receiving', 'Inbound Receiving'), ('picking', 'Order Picking'), ('packing', 'Packing & Verification'), ('shipping', 'Outbound Shipping'), ('qc', 'Quality Control'), ('inventory_control', 'Inventory Control & Audit')], max_length=30)),
                ('shift_start', models.TimeField(default='08:00:00')),
                ('shift_end', models.TimeField(default='17:00:00')),
                ('is_clocked_in', models.BooleanField(blank=True, default=False, null=True)),
                ('current_gps_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('current_gps_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('forklift_certified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeClockIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clock_in_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('clock_out_time', models.DateTimeField(blank=True, null=True)),
                ('clock_in_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('clock_in_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('total_hours_worked', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clock_ins', to='hr_tracking.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDailyTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('pick', 'Pick Task'), ('grn_qc', 'GRN Receiving & QC'), ('putaway', 'Putaway Task'), ('pack', 'Packing Station Task'), ('cycle_count', 'Cycle Counting')], max_length=30)),
                ('reference_id', models.CharField(max_length=100)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed / Exception')], default='pending', max_length=20)),
                ('items_handled_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to='hr_tracking.employee')),
            ],
            options={
                'indexes': [models.Index(fields=['employee', 'status'], name='idx_emp_tasks_active')],
            },
        ),
    ]
