# Generated by Django 4.2.30 on 2026-09-10 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_remove_warehouse_delivery_radius_km_and_more'),
        ('hr_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='master_data.warehouse'),
        ),
    ]
