# Generated by Django 5.1.15 on 2026-09-04 10:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('hr_tracking', '0001_initial'),
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('po_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('partially_received', 'Partially Received'), ('received', 'Fully Received'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='purchase_orders', to='catalog.vendor')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='master_data.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsReceiptNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grn_number', models.CharField(max_length=50, unique=True)),
                ('receipt_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(choices=[('pending_qc', 'Pending Quality Check'), ('qc_in_progress', 'QC in Progress'), ('completed', 'Completed & Putaway Done'), ('rejected', 'Rejected')], default='pending_qc', max_length=30)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_grns', to='hr_tracking.employee')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grn_records', to='master_data.warehouse')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='goods_receipt_notes', to='receiving.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordered_qty', models.IntegerField()),
                ('received_qty', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='receiving.purchaseorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='po_items', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='GRNItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('received_qty', models.IntegerField()),
                ('passed_qty', models.IntegerField(default=0)),
                ('rejected_qty', models.IntegerField(default=0)),
                ('damaged_photos_url', models.JSONField(blank=True, default=list)),
                ('qc_notes', models.TextField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='grn_items', to='catalog.batch')),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='receiving.goodsreceiptnote')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='grn_received_items', to='catalog.product')),
                ('putaway_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='putaway_items', to='master_data.location')),
                ('quarantine_location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='quarantined_items', to='master_data.location')),
                ('po_item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='grn_items', to='receiving.purchaseorderitem')),
            ],
        ),
    ]
