# Generated by Django 5.1.15 on 2026-09-06 08:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundProductItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inbound_no', models.CharField(db_index=True, max_length=50)),
                ('item_name', models.CharField(max_length=200)),
                ('product_id', models.CharField(blank=True, default='', max_length=50)),
                ('sku', models.CharField(db_index=True, max_length=64)),
                ('barcode', models.CharField(db_index=True, max_length=64)),
                ('batch_no', models.CharField(max_length=100)),
                ('serial_no', models.CharField(blank=True, max_length=100, null=True)),
                ('uom', models.CharField(default='Bag', max_length=30)),
                ('pack_size', models.CharField(default='1 unit', max_length=50)),
                ('expected_qty', models.IntegerField(default=0)),
                ('scanned_qty', models.IntegerField(default=0)),
                ('received_qty', models.IntegerField(default=0)),
                ('accepted_qty', models.IntegerField(default=0)),
                ('rejected_qty', models.IntegerField(default=0)),
                ('damaged_qty', models.IntegerField(default=0)),
                ('shortage_qty', models.IntegerField(default=0)),
                ('excess_qty', models.IntegerField(default=0)),
                ('mfg_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('best_before', models.CharField(default='', max_length=50)),
                ('remaining_shelf_life', models.CharField(default='', max_length=50)),
                ('temperature', models.CharField(default='25°C', max_length=30)),
                ('storage_condition', models.CharField(default='Ambient', max_length=50)),
                ('qc_status', models.CharField(default='Passed', max_length=50)),
                ('scanner_id', models.CharField(default='SCN-014', max_length=50)),
                ('receiver', models.CharField(default='Arjun', max_length=100)),
                ('scan_time', models.CharField(default='10:53', max_length=30)),
                ('status', models.CharField(default='Received', max_length=50)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InboundQCRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qc_id', models.CharField(max_length=50, unique=True)),
                ('inbound_no', models.CharField(db_index=True, max_length=50)),
                ('item_name', models.CharField(max_length=200)),
                ('sku', models.CharField(db_index=True, max_length=64)),
                ('batch_no', models.CharField(max_length=100)),
                ('inspected_qty', models.IntegerField(default=0)),
                ('accepted_qty', models.IntegerField(default=0)),
                ('rejected_qty', models.IntegerField(default=0)),
                ('damaged_qty', models.IntegerField(default=0)),
                ('qc_status', models.CharField(default='Passed', max_length=50)),
                ('damage_type', models.CharField(blank=True, default='', max_length=100)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=200)),
                ('inspector', models.CharField(default='Priya', max_length=100)),
                ('inspection_time', models.CharField(default='11:20', max_length=30)),
                ('evidence_photos', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-qc_id'],
            },
        ),
        migrations.CreateModel(
            name='InboundScanHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan_id', models.CharField(max_length=50, unique=True)),
                ('inbound_no', models.CharField(db_index=True, max_length=50)),
                ('scanner_id', models.CharField(default='SCN-014', max_length=50)),
                ('user', models.CharField(default='Arjun', max_length=100)),
                ('scan_type', models.CharField(default='Product Receive', max_length=50)),
                ('barcode', models.CharField(max_length=64)),
                ('item_name', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=64)),
                ('batch_no', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('location', models.CharField(default='Dock-03', max_length=50)),
                ('scan_time', models.CharField(default='10:53:12', max_length=30)),
                ('result', models.CharField(default='Valid', max_length=30)),
            ],
            options={
                'ordering': ['-scan_id'],
            },
        ),
        migrations.CreateModel(
            name='InboundShipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inbound_no', models.CharField(max_length=50, unique=True)),
                ('shipment_type', models.CharField(default='Supplier Delivery', max_length=50)),
                ('source', models.CharField(max_length=150)),
                ('warehouse', models.CharField(default='RJY-DS-001', max_length=50)),
                ('items_count', models.IntegerField(default=1)),
                ('expected_qty', models.IntegerField(default=0)),
                ('received_qty', models.IntegerField(default=0)),
                ('accepted_qty', models.IntegerField(default=0)),
                ('rejected_qty', models.IntegerField(default=0)),
                ('damaged_qty', models.IntegerField(default=0)),
                ('status', models.CharField(default='Receiving', max_length=50)),
                ('expected_arrival', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
