# Generated by Django 5.1.15 on 2026-09-05 14:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_batch_is_near_expiry_batch_markdown_price_and_more'),
        ('master_data', '0002_warehouse_delivery_radius_km_warehouse_is_dark_store_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SAPSystemConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_id', models.CharField(default='SAP_S4HANA_PRD', max_length=50)),
                ('sap_client', models.CharField(default='100', max_length=10)),
                ('plant_code', models.CharField(default='PLANT_1000', max_length=20)),
                ('company_code', models.CharField(default='ZIPPZO_CORP', max_length=20)),
                ('base_endpoint', models.URLField(default='https://sap-s4hana.enterprise.zippzo.internal:8443/sap/opu/odata/sap')),
                ('rfc_destination', models.CharField(default='RFC_S4HANA_WMS_CONN', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_connected', models.BooleanField(default=True)),
                ('last_heartbeat_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SAPIDocMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idoc_number', models.CharField(max_length=50, unique=True)),
                ('message_type', models.CharField(choices=[('MATMAS', 'Material Master Sync (MATMAS05)'), ('DESADV', 'Advanced Shipping Notice (DESADV01)'), ('WMMBID', 'Goods Movement / MIGO Posting (WMMBID02)'), ('INVENT', 'Cycle Count & Scrap Write-off (INVENT01)'), ('ORDERS', 'Stock Transport Order (ORDERS05)')], max_length=30)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound from SAP'), ('OUTBOUND', 'Outbound to SAP')], default='OUTBOUND', max_length=20)),
                ('status', models.CharField(choices=[('SUCCESS', 'Transmitted & Confirmed'), ('FAILED', 'Transmission Failed / Errored'), ('PENDING', 'Queued in Outbox'), ('RETRYING', 'Retrying Queue')], default='SUCCESS', max_length=20)),
                ('sap_document_number', models.CharField(blank=True, max_length=50, null=True)),
                ('movement_type', models.CharField(blank=True, help_text='e.g. 101, 301, 311, 551, 701', max_length=10, null=True)),
                ('payload_data', models.JSONField(default=dict)),
                ('xml_preview', models.TextField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['message_type', 'status', '-created_at'], name='idx_sap_msg_status'), models.Index(fields=['idoc_number'], name='idx_sap_idoc_num')],
            },
        ),
        migrations.CreateModel(
            name='StockTransportOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sto_number', models.CharField(max_length=50, unique=True)),
                ('sap_sto_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('sap_migo_doc', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DISPATCHED', 'Dispatched from Central Hub'), ('IN_TRANSIT', 'In Transit to Dark Store'), ('RECEIVED', 'Received at Dark Store'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('eta_minutes', models.IntegerField(default=30, help_text='Estimated arrival in minutes')),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stos', to=settings.AUTH_USER_MODEL)),
                ('destination_dark_store', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='incoming_stos', to='master_data.warehouse')),
                ('source_hub', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='outgoing_stos', to='master_data.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='STOItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_qty', models.IntegerField()),
                ('dispatched_qty', models.IntegerField(default=0)),
                ('received_qty', models.IntegerField(default=0)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sto_items', to='catalog.batch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sto_items', to='catalog.product')),
                ('sto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sap_integration.stocktransportorder')),
            ],
        ),
    ]
