# Generated by Django 5.1.15 on 2026-09-05 15:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_batch_is_near_expiry_and_more'),
        ('master_data', '0003_remove_warehouse_delivery_radius_km_and_more'),
        ('sap_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAPInboundDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sap_delivery_number', models.CharField(help_text='SAP Inbound Delivery # (e.g. 800192831)', max_length=50, unique=True)),
                ('po_reference', models.CharField(blank=True, help_text='SAP PO or STO Number', max_length=50, null=True)),
                ('source_plant', models.CharField(default='PLANT-1000 (Central Mother Hub)', max_length=50)),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_contact', models.CharField(blank=True, max_length=30, null=True)),
                ('expected_arrival', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Inward'), ('IN_PROGRESS', 'Receiving & QC in Progress'), ('COMPLETED', 'Completed & Posted to SAP'), ('FAILED', 'Sync Failed')], default='PENDING', max_length=30)),
                ('total_line_items', models.IntegerField(default=0)),
                ('total_expected_units', models.IntegerField(default=0)),
                ('total_received_units', models.IntegerField(default=0)),
                ('sap_gr_document_number', models.CharField(blank=True, help_text='SAP Material Document # upon 101 posting', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sap_inbound_deliveries', to='master_data.warehouse')),
            ],
            options={
                'verbose_name': 'SAP Inbound Delivery',
                'verbose_name_plural': 'SAP Inbound Deliveries',
                'ordering': ['-expected_arrival'],
            },
        ),
        migrations.CreateModel(
            name='SAPInboundLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sap_item_number', models.CharField(default='000010', max_length=10)),
                ('expected_qty', models.IntegerField()),
                ('received_qty', models.IntegerField(default=0)),
                ('passed_qty', models.IntegerField(default=0)),
                ('damaged_qty', models.IntegerField(default=0)),
                ('vendor_batch_code', models.CharField(blank=True, max_length=100, null=True)),
                ('mfg_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('suggested_putaway_bin', models.CharField(blank=True, max_length=50, null=True)),
                ('is_received', models.BooleanField(default=False)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sap_integration.sapinbounddelivery')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sap_inbound_items', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='SAPSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('ASN', 'Advanced Shipping Notice (Inbound Delivery)'), ('STO', 'Stock Transfer Order'), ('PO', 'Purchase Order'), ('GR_POSTING', 'Goods Receipt Posting (101)')], max_length=30)),
                ('reference_id', models.CharField(max_length=100)),
                ('payload_sent', models.JSONField(blank=True, default=dict)),
                ('response_received', models.JSONField(blank=True, default=dict)),
                ('http_status_code', models.IntegerField(default=200)),
                ('is_successful', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='SAPIDocMessage',
        ),
        migrations.DeleteModel(
            name='SAPSystemConfig',
        ),
        migrations.RemoveField(
            model_name='stoitem',
            name='sto',
        ),
        migrations.RemoveField(
            model_name='stoitem',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='stoitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='StockTransportOrder',
        ),
        migrations.DeleteModel(
            name='STOItem',
        ),
    ]
