# Generated by Django 5.1.15 on 2026-09-04 10:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('fulfillment', '0001_initial'),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rma_number', models.CharField(max_length=50, unique=True)),
                ('reason', models.CharField(choices=[('damaged', 'Damaged in Transit'), ('defective', 'Defective / Faulty Product'), ('wrong_item', 'Wrong Item Shipped'), ('customer_remorse', 'Customer Remorse / No Longer Needed')], max_length=50)),
                ('status', models.CharField(choices=[('initiated', 'RMA Initiated'), ('item_received', 'Item Received at Dock'), ('inspected', 'Inspected & Routed'), ('refund_approved', 'Refund Approved'), ('rejected', 'Return Rejected')], default='initiated', max_length=30)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='returns', to='catalog.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='return_orders', to='fulfillment.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('returned_qty', models.IntegerField()),
                ('inspection_result', models.CharField(blank=True, choices=[('restockable', 'Restockable (Return to Pick Zone)'), ('damaged_scrap', 'Damaged / Scrap Zone'), ('refurbish', 'Quarantine for Refurbishment')], max_length=50, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='return_items', to='catalog.batch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='return_items', to='catalog.product')),
                ('target_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restocked_returns', to='master_data.location')),
                ('rma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reverse_logistics.returnorder')),
            ],
        ),
    ]
