# Generated by Django 4.2.30 on 2026-09-09 14:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReasonCode',
            fields=[
                ('rc_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('SHORT_PICK', 'Short Pick'), ('DAMAGE', 'Damage'), ('DISCREPANCY', 'Discrepancy'), ('CHECK_IN_BREACH', 'Check-in Breach'), ('CANCEL', 'Cancel')], max_length=30)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('requires_photo', models.BooleanField(default=False)),
                ('requires_remark', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'reason_code',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emp_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(choices=[('PICKER', 'Picker'), ('PACKER', 'Packer'), ('SORTER', 'Sorter'), ('GRN_OP', 'GRN Operator'), ('QC', 'QC'), ('SUPERVISOR', 'Supervisor'), ('ADMIN', 'Admin')], max_length=20)),
                ('site_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLOCKED', 'Blocked')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
                'ordering': ['name'],
            },
        ),
    ]
