# Generated by Django 5.1.15 on 2026-09-04 10:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('zone_type', models.CharField(choices=[('bulk', 'Bulk Storage'), ('pick', 'Picking Zone'), ('quarantine', 'Quarantine Zone'), ('damaged', 'Damaged Zone'), ('staging', 'Staging Zone'), ('packing', 'Packing Zone'), ('shipping', 'Shipping Zone')], default='pick', max_length=30)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='master_data.warehouse')),
            ],
            options={
                'unique_together': {('warehouse', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aisle', models.CharField(max_length=20)),
                ('rack_number', models.CharField(max_length=20)),
                ('shelf_level', models.CharField(max_length=20)),
                ('bin_code', models.CharField(max_length=50, unique=True)),
                ('barcode_label', models.CharField(max_length=100, unique=True)),
                ('max_weight_kg', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('max_volume_cbm', models.DecimalField(decimal_places=4, default=2.5, max_digits=10)),
                ('is_occupied', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='master_data.zone')),
            ],
        ),
        migrations.CreateModel(
            name='LocationActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('putaway', 'Putaway'), ('pick', 'Pick'), ('transfer', 'Transfer'), ('cycle_count', 'Cycle Count')], max_length=30)),
                ('quantity', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='master_data.location')),
            ],
            options={
                'indexes': [models.Index(fields=['location', 'activity_type', '-timestamp'], name='idx_loc_act_time')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='master_data.category')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='master_data.warehouse')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'unique_together': {('warehouse', 'code')},
            },
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['zone', 'aisle', 'rack_number', 'shelf_level'], name='idx_loc_zone_aisle'),
        ),
    ]
