# Generated by Django 5.1.15 on 2026-09-05 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='delivery_radius_km',
            field=models.DecimalField(decimal_places=2, default=3.5, max_digits=5),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_dark_store',
            field=models.BooleanField(default=True, help_text='True for 10-minute micro-fulfillment center'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='parent_hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dark_stores', to='master_data.warehouse'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AlterField(
            model_name='zone',
            name='zone_type',
            field=models.CharField(choices=[('bulk', 'Bulk Pallet Storage'), ('pick', 'Ambient Pick Aisle'), ('chilled', 'Chilled Cold Room (2°C - 4°C)'), ('frozen', 'Deep Freezer (-18°C)'), ('produce', 'Fresh Fruits & Veg Crate Racks'), ('fast_pick', 'High-Velocity Pick Face'), ('quarantine', 'Dock Quarantine'), ('damaged', 'Damaged & Waste Zone'), ('staging', 'Rider Dispatch Staging'), ('packing', 'Packing Table'), ('shipping', 'Outbound Dispatch Dock')], default='pick', max_length=30),
        ),
    ]
