# Generated by Django 5.1.15 on 2026-09-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_warehouse_delivery_radius_km_warehouse_is_dark_store_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='delivery_radius_km',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='is_dark_store',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='parent_hub',
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='country',
            field=models.CharField(default='USA', max_length=100),
        ),
        migrations.AlterField(
            model_name='zone',
            name='zone_type',
            field=models.CharField(choices=[('bulk', 'Bulk Storage'), ('pick', 'Picking Zone'), ('quarantine', 'Quarantine Zone'), ('damaged', 'Damaged Zone'), ('staging', 'Staging Zone'), ('packing', 'Packing Zone'), ('shipping', 'Shipping Zone')], default='pick', max_length=30),
        ),
    ]
