# Generated by Django 5.1.15 on 2026-09-04 10:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fulfillment', '0001_initial'),
        ('hr_tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan_verified_qty', models.IntegerField(default=0)),
                ('packaging_type', models.CharField(default='Standard Box', max_length=50)),
                ('actual_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('in_progress', 'Scanning in Progress'), ('verified', 'Scan Verified & Matched'), ('packed', 'Sealed & Ready for Shipping'), ('mismatch_hold', 'Barcode Mismatch / On Hold')], default='pending', max_length=30)),
                ('error_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_tasks', to='fulfillment.salesorder')),
                ('packed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packed_tasks', to='hr_tracking.employee')),
                ('pick_task', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='packing_task', to='fulfillment.picktask')),
            ],
        ),
    ]
