# Generated by Django 5.1.15 on 2026-09-06 08:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('packing_id', models.CharField(max_length=50, unique=True)),
                ('order_id', models.CharField(db_index=True, max_length=50)),
                ('pick_task_id', models.CharField(db_index=True, max_length=50)),
                ('package_id', models.CharField(db_index=True, max_length=50)),
                ('packing_station', models.CharField(default='PACK-04', max_length=50)),
                ('packer', models.CharField(default='Priya', max_length=100)),
                ('items_expected', models.IntegerField(default=1)),
                ('items_verified', models.IntegerField(default=1)),
                ('units', models.IntegerField(default=1)),
                ('package_count', models.IntegerField(default=1)),
                ('weight', models.CharField(default='7.8 kg', max_length=30)),
                ('dimensions', models.CharField(default='40×30×25 cm', max_length=50)),
                ('package_type', models.CharField(default='Standard Box', max_length=50)),
                ('package_barcode', models.CharField(default='PKG890123', max_length=64)),
                ('seal_no', models.CharField(default='SEAL-48219', max_length=50)),
                ('qc_status', models.CharField(default='Passed', max_length=30)),
                ('packed_at', models.CharField(default='13:05', max_length=30)),
                ('status', models.CharField(default='Packed', max_length=50)),
            ],
            options={
                'ordering': ['-packing_id'],
            },
        ),
    ]
