# Generated by Django 4.2.30 on 2026-09-09 14:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wms_master', '0001_initial'),
        ('wms_platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleCount',
            fields=[
                ('count_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('BIN', 'Bin'), ('SKU', 'SKU'), ('BLIND', 'Blind')], default='BIN', max_length=10)),
                ('scope', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PLANNED', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_counts', to='wms_platform.user')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_counts', to='wms_master.site')),
            ],
            options={
                'db_table': 'cycle_count',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReplenishmentTask',
            fields=[
                ('rep_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty', models.IntegerField(default=0)),
                ('trigger', models.CharField(choices=[('ALLOCATION', 'Allocation'), ('THRESHOLD', 'Threshold')], default='THRESHOLD', max_length=15)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replenishments', to='wms_platform.user')),
                ('from_bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replen_from', to='wms_master.bin')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishments', to='wms_master.site')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishments', to='wms_master.sku')),
                ('to_bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replen_to', to='wms_master.bin')),
            ],
            options={
                'db_table': 'replenishment_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CycleCountLine',
            fields=[
                ('line_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_qty', models.IntegerField(default=0)),
                ('counted_qty', models.IntegerField(default=0)),
                ('variance', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('MATCHED', 'Matched'), ('VARIANCE', 'Variance'), ('ADJUSTED', 'Adjusted')], default='PENDING', max_length=15)),
                ('bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='count_lines', to='wms_master.bin')),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='wms_optional.cyclecount')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_lines', to='wms_master.sku')),
            ],
            options={
                'db_table': 'cycle_count_line',
            },
        ),
    ]
