# Generated by Django 5.1.15 on 2026-09-04 10:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('hr_tracking', '0001_initial'),
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_qty', models.IntegerField()),
                ('allocated_qty', models.IntegerField(default=0)),
                ('picked_qty', models.IntegerField(default=0)),
                ('shipped_qty', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='order_items', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='PickWave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wave_number', models.CharField(max_length=50, unique=True)),
                ('strategy', models.CharField(choices=[('zone_pick', 'Zone Pick'), ('batch_pick', 'Batch Pick'), ('single_order_pick', 'Single Order Pick')], default='batch_pick', max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_waves', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_waves', to='master_data.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='PickTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_to_pick', models.IntegerField()),
                ('quantity_picked', models.IntegerField(default=0)),
                ('sequence_route_order', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('exception', 'Exception / Damaged')], default='open', max_length=30)),
                ('exception_reason', models.CharField(blank=True, choices=[('damaged_stock', 'Damaged Stock in Bin'), ('bin_empty', 'Bin is Empty / Stock Discrepancy'), ('wrong_barcode', 'Item Barcode Mismatch'), ('expired_stock', 'Stock Expired')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pick_tasks', to='hr_tracking.employee')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pick_tasks', to='catalog.batch')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_tasks', to='fulfillment.orderitem')),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pick_tasks', to='master_data.location')),
                ('target_staging_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staging_tasks', to='master_data.location')),
                ('wave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='fulfillment.pickwave')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('shipping_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_deadline', models.DateTimeField()),
                ('priority', models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('same_day', 'Same Day')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('allocated', 'Allocated'), ('partially_allocated', 'Partially Allocated'), ('picking', 'Picking in Progress'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='confirmed', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sales_orders', to='catalog.customer')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='master_data.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fulfillment.salesorder'),
        ),
    ]
