# Generated by Django 5.1.15 on 2026-09-06 08:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickingItemDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pick_task', models.CharField(db_index=True, max_length=50)),
                ('order_id', models.CharField(db_index=True, max_length=50)),
                ('sequence', models.IntegerField(default=1)),
                ('item_name', models.CharField(max_length=200)),
                ('sku', models.CharField(db_index=True, max_length=64)),
                ('barcode', models.CharField(db_index=True, max_length=64)),
                ('batch_no', models.CharField(max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('required_qty', models.IntegerField(default=1)),
                ('available_qty', models.IntegerField(default=0)),
                ('reserved_qty', models.IntegerField(default=0)),
                ('picked_qty', models.IntegerField(default=0)),
                ('short_qty', models.IntegerField(default=0)),
                ('damaged_qty', models.IntegerField(default=0)),
                ('source_location', models.CharField(default='A01-R02-S01-B08', max_length=50)),
                ('location_barcode', models.CharField(default='LOC-A01-R02-S01-B08', max_length=64)),
                ('scanner_id', models.CharField(default='SCN-021', max_length=50)),
                ('picker', models.CharField(default='Rahul', max_length=100)),
                ('scan_time', models.CharField(default='12:35', max_length=30)),
                ('fefo_applied', models.CharField(default='Yes', max_length=10)),
                ('pick_method', models.CharField(default='Wave', max_length=50)),
                ('status', models.CharField(default='Picked', max_length=50)),
            ],
            options={
                'ordering': ['pick_task', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='PickingScanHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan_id', models.CharField(max_length=50, unique=True)),
                ('pick_task', models.CharField(db_index=True, max_length=50)),
                ('order', models.CharField(db_index=True, max_length=50)),
                ('scanner', models.CharField(default='SCN-021', max_length=50)),
                ('picker', models.CharField(default='Rahul', max_length=100)),
                ('scan_type', models.CharField(default='Product Scan', max_length=50)),
                ('sku', models.CharField(blank=True, default='', max_length=64)),
                ('barcode', models.CharField(max_length=64)),
                ('batch', models.CharField(blank=True, default='', max_length=100)),
                ('location', models.CharField(default='A01-R02-S01-B08', max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('result', models.CharField(default='Valid', max_length=30)),
                ('scan_time', models.CharField(default='12:35:12', max_length=30)),
            ],
            options={
                'ordering': ['-scan_id'],
            },
        ),
        migrations.CreateModel(
            name='PickingTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pick_task_id', models.CharField(max_length=50, unique=True)),
                ('order_id', models.CharField(db_index=True, max_length=50)),
                ('wave_id', models.CharField(db_index=True, max_length=50)),
                ('order_type', models.CharField(default='Customer Order', max_length=50)),
                ('priority', models.CharField(default='High', max_length=20)),
                ('warehouse', models.CharField(default='RJY-DS-001', max_length=50)),
                ('picker', models.CharField(default='Rahul', max_length=100)),
                ('zone', models.CharField(default='Mixed', max_length=50)),
                ('pick_route', models.CharField(default='A01 → A04 → A07', max_length=150)),
                ('sequence', models.IntegerField(default=1)),
                ('total_items', models.IntegerField(default=1)),
                ('total_units', models.IntegerField(default=1)),
                ('picked_items', models.IntegerField(default=0)),
                ('picked_units', models.IntegerField(default=0)),
                ('exceptions', models.IntegerField(default=0)),
                ('started_at', models.CharField(default='12:30', max_length=30)),
                ('completed_at', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.CharField(default='In Progress', max_length=50)),
            ],
            options={
                'ordering': ['-pick_task_id'],
            },
        ),
    ]
